### ISSUE TITLE
챗GPT로 생성한 스키마 쿼리(sql)

### ISSUE THREAD

**Issue by jaeunkm** [SeSAC-minguinho/Minguinho#18]
CREATE TABLE Parents (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    provider VARCHAR(255) NOT NULL,
    provider_id VARCHAR(255) UNIQUE NOT NULL,
    auth_token TEXT NOT NULL
);

-- Create table for Children
CREATE TABLE Children (
    id SERIAL PRIMARY KEY,
    parent_id INT REFERENCES Parents(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL
);

-- Create table for Conversations
CREATE TABLE Conversations (
    id SERIAL PRIMARY KEY,
    child_id INT REFERENCES Children(id) ON DELETE CASCADE,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(50) NOT NULL
);

-- Create table for Messages
CREATE TABLE Messages (
    id SERIAL PRIMARY KEY,
    conversation_id INT REFERENCES Conversations(id) ON DELETE CASCADE,
    text TEXT NOT NULL,
    sender_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create table for Summaries
CREATE TABLE Summaries (
    id SERIAL PRIMARY KEY,
    conversation_id INT REFERENCES Conversations(id) ON DELETE CASCADE,
    summary_text TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

- [x] 확인부탁드립니다.

**Comment by azaraks** [comment]
기능하는데 문제 없어 보입니다. 👍 
@jaeunkm , sqlalchemy로 테이블 생성과 쿼리도 담당해주시면 좋겠습니다.
본 이슈는 Close합니다.
